### ISSUE TITLE
User-Resolver: sha1() expects parameter 1 to be string, int given

### ISSUE THREAD

**Issue by heladrion** [artisansdk/ratelimiter#13]
Hello!

I'm getting the error
"sha1() expects parameter 1 to be string, int given" 
in the `Resolvers\User.php` file at `sha1($user->getAuthIdentifier());`

```php
    public function key(): string
    {
        if ($user = $this->resolveUser()) {
            return sha1($user->getAuthIdentifier());
        }
```

The result of `getAuthIdentifier()` is the `id` of the user table for me. Due to the new introduced `declare(strict_types=1);` at the top and that sha1 doesn't allow an int, it fails :(
According to the documentation the `getAuthIdentifier` should actually return an email, maybe a wrong configuration from me?

I copied the file and changed it now to the following.
```php
        if ($user = $this->resolveUser()) {
            return sha1((string) $user->getAuthIdentifier());
        }
```
But I think this should be changed.

I would create a pull request but I've absolutely no idea how to. 😅

**Comment by dalabarge** [comment]
Thanks for the catch. There's a bit of an assumption going on within the `Resolver\User` class that the resolved user is an `Authenticatable` user model. Then there's the assumption that the `getAuthIdentifier()` would return the email address instead of the ID though the default implementation of the `Authenticatable` trait (not the interface) is that it does return the ID, and that's assumed to be an integer instead of a UUID string. Anyway, it's been merged and fixed with tag `1.0.2` so just bump to that version as minimum.
