### ISSUE TITLE
Setting 24 hour rate limit

### ISSUE THREAD

**Issue by timersys** [artisansdk/ratelimiter#18]
This is not a bug, I think I just I do not understand how to set the limits on custom resolvers.

I created a custom resolver for ratings that uses path + IP as the key. Basically what I need to do is to allow all IPs to only vote once per day per game.
So every IP can vote multiple games, but only once per day. I set my resolver like this but is not working  as it should 

`<?php
namespace App\Http\RateResolvers;

use ArtisanSdk\RateLimiter\Resolvers\User as Resolver;
use Illuminate\Http\Request;

class RatingResolver extends Resolver {
	protected $max = '1'; 
	protected $rate = '0.00001157'; 
	protected $duration = 3600*24; 

	public function __construct(Request $request)
	{
		parent::__construct($request, $this->max, $this->rate, $this->duration);
	}

	/**
	 * Get the resolver key used by the rate limiter for the unique request.
	 */
	public function key(): string
	{
		$prefix = parent::key() . $this->request->ip();

		$route = $this->request->route();

		if ($path = $this->request->path() ) {
			return $prefix.':'.sha1($path);
		}

		if ($name = $route->getName()) {
			return $prefix.':'.sha1($name);
		}

		$class = $route->getAction('uses');
		if (! is_null($class) && is_string($class)) {
			return $prefix.':'.sha1($class);
		}

		return $prefix.':'.sha1($route->uri());
	}
}`

**Comment by dalabarge** [comment]
Thank you for using the package. We are working on improving the readme as we get some questions around the configuration quite often.

The low rates that you are using are not really what this package was designed for. Anything less than one request per second is going to have more potential for floating point rounding errors so accuracy is not guaranteed when trying to track 1 hit every 24 hours. This package was more designed for 100 requests per minute kind of logic with a tolerance for some inaccuracy in the requesting throttling due to rounding errors and cache latency. It's actually less about the rate and more about the max number of requests: this package was designed to track a larger volume of requests total. While you can reduce 120 requests per minute (a rate of 2) to 2 requests per second (a rate of 2), any multiple of 2 requests per second would tolerate a bit of slop in the throttling mechanism. For example 20 max requests in 10 seconds would still be a rate of 2 but 10 requests in 20 seconds would be a rate of 0.5 just as 1 request every 2 seconds is also a rate of 0.5. While this package can work for either rate, it's more designed for 1+ rates or fractional rates but with higher maximums than 1. Anything with a low max or very small fractional rates might be better suited for a direct query lookup and a conditional guard within the controller where the game and user are already known.

Nevertheless, let me see if I can address your issue:

1. Your `$max` and `$rate` properties should really be `int` and `float` respectively. Strings are interpreted differently by the `User@parse()` resolver function. Strings are used to lookup attributes off of the user that is resolved. For example `$user->$max` if `$max='max_requests_allowed'` or something. So if `$user->max_requests_allowed = 1` then the limiter would use `$max=1` effectively.
2. Note there are 86400 seconds in a day so `$max = 1` divided by 86400 would give `$rate = 0.00001157407407` and you rounded your `$rate` to 8 digits of precision (likely close enough!).
3. If you only want to use path and IP address (remember shared IPs are a thing!) and aren't interested in distinguishing between guest users and anonymous users then I'd recommend you not extend the base `User` resolver and just implement the resolver yourself (see below).
4. If you do want to treat anonymous users as one group separated by IP and path then I'd recommend using user ID and path for authenticated users as that prevents users from IP address hopping using a proxy: for that you can just use the default `Route` resolver which extends the user by default. The `Route` resolver does assume you use a named route or at minimum an unique controller action. If you need the path instead then see suggested resolver below.
5. You hardcode your resolver settings, which is entirely your call, but a better way is to bind it at the route configuration level: `Games::class.'|1|0.00001157,86400`. You can use that as the value of an alias in `middleware.php` so you can define it in one place while using it on multiple routes if need be. Otherwise look into extending the `ArtisanSdk\RateLimiter\Middleware@makeResolver()` to not construct a new resolver like it does but to instead just use the one passed into the constructor as is: you can use the `AppServiceProvider` to pass a default resolver.
6. I'll point out that the `$duration` of `3600 * 24` is `86400` seconds which is the duration of the timeout if the rate limiting is exceeded. The penalty for attempting to rate the game more than once in 24h is 24h from the time of the ban. It's a penalty but might need to be more punitive by setting to 48h or 72h to discourage any bad behavior. Further you may want to implement a nested or cascading bucket that disables all ratings by a given user when they exceed the rate limit for any one game. For that you might have to get into customizing the bucket or using events. If you listen for a rate limit to be exceeded event then you can trigger the timeout manually on another more generic bucket that tracks hits for gaming ratings by that particular user. Added advantage is you could also log hits to the user bucket when the game bucket is hit so that you can throttle how many ratings a day a user can do across all games while still preventing too may ratings of a particular game.
7. You mention a game rating/voting as being the thing rate limited - does this game have an Eloquent model? If it does, you could just setup the rate limiter on the game route (see Middleware documentation in README) and instead have a `GameRating` resolver that resolves the key from the game ID instead of the request path. You might have to get the game ID from the route bindings but it might be more accurate to rate limit on the ID instead of a path. You could also check to see if the current user has played the game (assuming there's player logs and the user is authenticated) and throw an exception if they are attempting to rate a game they haven't played.

Hope that gives you insights. See below for some possible resolvers. Please comment with what you wind up getting to work.

A resolver for path and IP address without consideration of the user ID:

```
<?php

declare(strict_types=1);

namespace App\Http\Rates;

use ArtisanSdk\RateLimiter\Contracts\Resolver;
use RuntimeException;
use Symfony\Component\HttpFoundation\Request;

class Games implements Resolver
{
    /**
     * The request available to the resolver.
     *
     * @var \Illuminate\Http\Request
     */
    protected $request;

    /**
     * The max number of requests allowed by the rate limiter.
     *
     * @var int
     */
    protected $max;

    /**
     * The replenish rate in requests per second for the rate limiter.
     *
     * @var int
     */
    protected $rate;

    /**
     * The duration in seconds the rate limiter will timeout.
     *
     * @var int
     */
    protected $duration;

    /**
     * Setup the resolver.
     *
     * @param \Illuminate\Http\Request $request
     * @param int|string               $max
     * @param int|float|string         $rate
     * @param int|string               $duration
     */
    public function __construct(Request $request, $max = null, $rate = null, $duration = null)
    {
        $this->request = $request;
        $this->max = $max ?? 1;
        $this->rate = $rate ?? 0.00001157;
        $this->duration = $duration ?? 3600 * 24;
    }

    /**
     * Get the resolver key used by the rate limiter for the unique request.
     *
     * @throws \RuntimeException
     */
    public function key(): string
    {
        if ($path = $this->request->path()) {
            return sha1(ltrim($path.'|'.$this->request->ip(), '|'));
        }

        throw new RuntimeException('Unable to generate the request signature. Route unavailable.');
    }

    /**
     * Get the max number of requests allowed by the rate limiter.
     */
    public function max(): int
    {
        return $this->max;
    }

    /**
     * Get the replenish rate in requests per second for the rate limiter.
     */
    public function rate(): float
    {
        return $this->rate;
    }

    /**
     * Get the duration in seconds the rate limiter will timeout.
     */
    public function duration(): int
    {
        return $this->duration;
    }
 }   
```

Or for path and IP address for guests but user ID for authenticated users you could use (notice no rate limiting properties set on this instance since you can configure those via the `bind()` in the `AppServiceProvider` by passing to the `__construct()` in the right order or even at the route configuration level).

```
<?php

declare(strict_types=1);

namespace App\Http\Rates;

use ArtisanSdk\RateLimiter\Resolvers\User as Resolver;
use RuntimeException;

class Games extends Resolver
{
    /**
     * Get the resolver key used by the rate limiter for the unique request.
     */
    public function key(): string
    {
        $prefix = parent::key(); // a hash of the User ID or the domain + IP address

        if ($path = $this->request->path()) {
            return $prefix.':'.sha1($path);
        }

        throw new RuntimeException('Unable to generate the request signature. Path unavailable.');
    }
}
```
